// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBietC4RcslcWrS279P9r70J6nzK32EEOM',
    appId: '1:795353050158:web:21e74bbf3d4551181cc3bf',
    messagingSenderId: '795353050158',
    projectId: 'movieapp-44458',
    authDomain: 'movieapp-44458.firebaseapp.com',
    storageBucket: 'movieapp-44458.firebasestorage.app',
    measurementId: 'G-3JH420GXKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUf0ACc-f2w7ERCXFGlr6eBkmPdeK_tUI',
    appId: '1:795353050158:android:85f3d1446503a1e81cc3bf',
    messagingSenderId: '795353050158',
    projectId: 'movieapp-44458',
    storageBucket: 'movieapp-44458.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpQNEZpq66OjVSYLXeb6AEhufTRHe2xc',
    appId: '1:795353050158:ios:38f1e5c31b63d84b1cc3bf',
    messagingSenderId: '795353050158',
    projectId: 'movieapp-44458',
    storageBucket: 'movieapp-44458.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpQNEZpq66OjVSYLXeb6AEhufTRHe2xc',
    appId: '1:795353050158:ios:38f1e5c31b63d84b1cc3bf',
    messagingSenderId: '795353050158',
    projectId: 'movieapp-44458',
    storageBucket: 'movieapp-44458.firebasestorage.app',
    iosBundleId: 'com.example.projectFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBietC4RcslcWrS279P9r70J6nzK32EEOM',
    appId: '1:795353050158:web:a0c345dadc2a07db1cc3bf',
    messagingSenderId: '795353050158',
    projectId: 'movieapp-44458',
    authDomain: 'movieapp-44458.firebaseapp.com',
    storageBucket: 'movieapp-44458.firebasestorage.app',
    measurementId: 'G-LJK4VJ4YHE',
  );
}
